---
title: "Dirty Data Project - Task 2 - Cakes"
author: John Wood
output: html_notebook
---

```{r include = FALSE}
# Load required libraries

library(tidyverse)
library(here)

```

```{r include = FALSE}
# read in clean csv files

cakes <- read_csv(here("clean_data/cakes_clean.csv"))

```

## Q1: Which cake has the most cocoa in it?

```{r echo = FALSE}
cakes %>% 
  filter(ingredient == "Cocoa") %>% 
  slice_max(quantity)
```

## Q2 For sponge cake, how many cups of ingredients are used in total?

```{r echo = FALSE}

cakes %>% 
  filter(cake == "Sponge" & measure == "cup")  %>% 
  summarise(total_cups = sum(quantity))

```

## Q3 How many ingredients are measured in teaspoons?

```{r echo = FALSE}

cakes %>% 
  distinct(ingredient, measure) %>% 
  filter(measure == "teaspoon") %>% 
  count(measure, name = "num_ingredients")
 
```

## Q4 Which cake has the most unique ingredients?

```{r echo = FALSE}
# An ingredient is used if quantity > 0. 
# The condition quantity > 0 will return TRUE (value = 1).
# So sum this to get total number of unique ingredients.

cakes %>% 
  group_by(cake) %>%
  summarise(unique_ingredients = sum(quantity > 0)) %>% 
  slice_max(unique_ingredients)

```

## Q5 Which ingredients are used only once?

```{r echo = FALSE}

# An ingredient is used if quantity > 0. 
# The condition quantity > 0 will return TRUE (value = 1).
# So sum this to get total number of times used..

cakes %>% 
  group_by(ingredient) %>%
  summarise(times_used = sum(quantity > 0)) %>% 
  filter(times_used == 1)

```

